### PR TITLE
Create ModTestStuff.json

### PR DESCRIPTION
**Pull request by micahwhitsel**

### CODE REVIEW

**Review by uaon — COMMENTED** [review]
This isn't going to work,
The `` "KEY": "VALUE" `` is incorrectly setup.
Imagine if KEY = Directory name
Imagine if VALUE = app id to download from steamworkshop into that directory.

Linux is gonna flip out with a lot of these file names, such as ``F/A-18E/F Super Hornet 2020``
or ``Lambs_Danger.fsm`` -- you couldn't even make a folder with a .ext on it in windows.

Also none of this include ARMA's requirement of having mods start with ``@`` symbol.

chrome_GaqjqBDnCs

**Comment by micahwhitsel** [comment]
> This isn't going to work,
> The `"KEY": "VALUE"` is incorrectly setup.
> Imagine if KEY = Directory name
> Imagine if VALUE = app id to download from steamworkshop into that directory.
> 
> Linux is gonna flip out with a lot of these file names, such as `F/A-18E/F Super Hornet 2020`
> or `Lambs_Danger.fsm` -- you couldn't even make a folder with a .ext on it in windows.
> 
> Also none of this include ARMA's requirement of having mods start with `@` symbol.
> 
> chrome_GaqjqBDnCs

Updated, I just made a little text joiner to create the structure for all this so I wasn't thinking about the folder name stuff. I'll make adjustments to that to make those adjustments. Need to add short names for all the mods

**Comment by uaon** [comment]
> > This isn't going to work,
> > The `"KEY": "VALUE"` is incorrectly setup.
> > Imagine if KEY = Directory name
> > Imagine if VALUE = app id to download from steamworkshop into that directory.
> > Linux is gonna flip out with a lot of these file names, such as `F/A-18E/F Super Hornet 2020`
> > or `Lambs_Danger.fsm` -- you couldn't even make a folder with a .ext on it in windows.
> > Also none of this include ARMA's requirement of having mods start with `@` symbol.
> > chrome_GaqjqBDnCs
> 
> Updated, I just made a little text joiner to create the structure for all this so I wasn't thinking about the folder name stuff. I'll make adjustments to that to make those adjustments. Need to add short names for all the mods

Gotcha, the names don't really matter, all the mods could be named in numbers like ``@1``, ``@2``..etc
none of this affects what players see or steam-api, 

see Battlemetrics for the server itself to tell what is shown on lookup.
[](https://www.battlemetrics.com/servers/arma3/11346593)

we usually just name them short so its easier to note on the logs as well as not have a massive startup mod parameter that obliterates the char limit. this also affects what the mod folders are called in the container so we try to limit them to non-CameLCasE and leave out any special chars like ``/`` or ``-`` if we can help it.

**Comment by micahwhitsel** [comment]
@uaon If that looks good could this be merged? I can merge but don't want to be preemptive for now. This was a direct copy past from my config generator from sheets

**Comment by uaon** [comment]
looks good to me, was just bringing up why and how we do it, cause initially a commit made to the repo means u are ready to start merging -- typically I don't commit to a repo until I've made all the changes I feel are needed... and add commits after testing and I realize I screwed up after testing. lol

Though I guess the commit process is different for each individual.

**Comment by micahwhitsel** [comment]
> looks good to me, was just bringing up why and how we do it, cause initially a commit made to the repo means u are ready to start merging -- typically I don't commit to a repo until I've made all the changes I feel are needed... and add commits after testing when I realize I screwed up after testing. lol
> 
> Though I guess the commit process is different for each individual.

I'm going to clean up my tool some so that hopefully people can use it in the future and just pick the mods they can in the drop-down, select what's optional with a checkbox, and then copy-paste the config. Should make things cleaning in the future. I'll go ahead and merge though, appreciate the help

**Pull request merged**
